# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish

on:
  workflow_dispatch:
  
  push:
    branches: [ master ]

jobs:
  publish-coding:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node-v12
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: set-git-config
        run: |
          git config user.email "sjfkai@163.com"
          git config user.name "sjfkai"
      - name: deploy
        env:
          GH_PAGES_REPO: 'https://${{secrets.CODING_USER}}@e.coding.net/sjfkai/geocoding/geocoding.git'
          GH_PAGES_BRANCH: master
        run: |
          npm install
          npm run deploy
        
