# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish

on:
  push:
    branches: [ master ]

jobs:
  publish-coding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm run deploy
        env:
          GH_PAGES_REPO: 'https:${{secrets.CODING_USER}}@e.coding.net/sjfkai/geocoding/geocoding.git'
          GH_PAGES_BRANCH: master
